artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  papers_path: papers.txt
  papers: []

vector_db:
  root_dir: chroma_db
  embedding_model: "text-embedding-3-small"
  cache_dir: Path
  db_name: "researchbot"
  batch_size: 100

